SELECT K.YEARS AS YEAR, (K.MAXNUM-E.SIZE_OF_COLONY) AS YEAR_DEV, E.ID
FROM ECOLI_DATA E 
LEFT JOIN (
    SELECT MAX(T.SIZE_OF_COLONY) MAXNUM, YEAR(T.DIFFERENTIATION_DATE) YEARS
    FROM ECOLI_DATA T
    GROUP BY YEAR(T.DIFFERENTIATION_DATE)
) K ON YEAR(E.DIFFERENTIATION_DATE) = K.YEARS
ORDER BY K.YEARS ASC, YEAR_DEV ASC